Vagrant.configure("2") do |config|
  (1..2).each do |i|
       config.vm.define "kn#{i}" do |node|
           # 设置虚拟机的Box
           node.vm.box = "centos/7"
           # 设置磁盘大小
           node.vm.disk :disk, size: "50GB", primary: true

           # 设置虚拟机的主机名
           node.vm.hostname="kn#{i}"
           
           # 设置虚拟机的网络
           node.vm.network "public_network"
           node.vm.network "private_network", ip: "192.168.56.#{100+i}", netmask: "255.255.255.0", gateway: "192.168.56.1"

           # VirtaulBox相关配置
           node.vm.provider "virtualbox" do |v|
               # 设置虚拟机的名称
               v.name = "kn#{i}"
               # 设置虚拟机的内存大小
               v.memory = 4096
               # 设置虚拟机的CPU个数
               v.cpus = 1.5
           end

           config.vm.provision "shell", inline: <<-SHELL
              # 为root配置SSH密钥对
              mkdir /root/.ssh/ -p
              chmod 700 /root/.ssh/
              cd /root/.ssh/
              cp /vagrant/keys/id_rsa . -rf
              chmod 600 ./id_rsa
              
              cp /vagrant/keys/authorized_keys . -rf
              chmod 600 ./authorized_keys
           SHELL
       end
  end
end